name: Build and Release macOS App

on:
  push:
    branches:
      - main
    tags:
      - 'v*' # Trigger on tags like v1.0.0

jobs:
  build-and-release:
    runs-on: macos-latest
    permissions:
      contents: write # Grant write permission for GITHUB_TOKEN to create releases

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Xcode version
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '16.2.0'

    - name: Get App Version and Release Tag
      id: get_version
      run: |
        VERSION=$(/usr/libexec/PlistBuddy -c "Print CFBundleShortVersionString" LockIt/Info.plist)
        BUILD_NUMBER=$(/usr/libexec/PlistBuddy -c "Print CFBundleVersion" LockIt/Info.plist)
        echo "APP_VERSION=$VERSION" >> $GITHUB_ENV
        echo "APP_BUILD_NUMBER=$BUILD_NUMBER" >> $GITHUB_ENV

        # Extract tag name if triggered by a tag push
        if [[ "${{ github.ref }}" == refs/tags/v* ]]; then
          RELEASE_VERSION=$(echo "${{ github.ref }}" | sed -e "s/refs\/tags\///g")
        else
          RELEASE_VERSION="v$VERSION" # Fallback to Info.plist version if not a tag
        fi
        echo "RELEASE_VERSION=$RELEASE_VERSION" >> $GITHUB_ENV

    - name: Build Application
      run: |
        xcodebuild clean build \
          -workspace LockIt.xcodeproj/project.xcworkspace \
          -scheme LockIt \
          -configuration Release \
          -destination "platform=macOS" \
          -derivedDataPath build \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO

    - name: Create DMG
      run: |
        APP_NAME="LockIt"
        APP_BUNDLE_PATH="build/Build/Products/Release/${APP_NAME}.app"
        DMG_NAME="${APP_NAME}-${{ env.RELEASE_VERSION }}.dmg"
        TEMP_DMG_NAME="${DMG_NAME}.temp.dmg"
        
        echo "Creating DMG for: $APP_BUNDLE_PATH"
        echo "Output DMG: $DMG_NAME"

        # Create a new blank disk image
        hdiutil create -ov -fs HFS+ -volname "${APP_NAME}" -size 100m "${TEMP_DMG_NAME}"

        # Mount the disk image
        hdiutil attach "${TEMP_DMG_NAME}" -mountpoint "/Volumes/${APP_NAME}"

        # Copy the application into the disk image
        cp -R "${APP_BUNDLE_PATH}" "/Volumes/${APP_NAME}/"

        # Create a symlink to the Applications folder
        ln -s /Applications "/Volumes/${APP_NAME}/Applications"

        # Unmount the disk image
        hdiutil detach "/Volumes/${APP_NAME}"

        # Convert the disk image to a compressed, read-only format
        hdiutil convert "${TEMP_DMG_NAME}" -format UDBZ -o "${DMG_NAME}"

        # Remove the temporary disk image
        rm "${TEMP_DMG_NAME}"

    - name: Create GitHub Release
      if: startsWith(github.ref, 'refs/tags/v') # Only create release on tag pushes
      uses: softprops/action-gh-release@v1
      with:
        files: LockIt-${{ env.RELEASE_VERSION }}.dmg
        name: Release ${{ env.RELEASE_VERSION }}
        tag_name: ${{ github.ref }}
        body: |
          # LockIt ${{ env.RELEASE_VERSION }}

          This is an automated release.
          
          ## Changes
          (Add release notes here)
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
